import type { NextPage } from 'next';
import Head from 'next/head';
import Explore from '../components/Explore';
import Hero from '../components/Hero';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Lift Off</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Explore />
    </>
  );
};

export default Home;
