import type { NextPage } from 'next';
import Head from 'next/head';
import Details from '../components/Details';
import Explore from '../components/Explore';
import Hero from '../components/Hero';
import Liftoff from '../components/Liftoff';
import Testimonials from '../components/Testimonials';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Lift Off</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Explore />
      <Details />
      <Testimonials />
      <Liftoff />
    </>
  );
};

export default Home;
